import type { Metadata } from "next";
import "./globals.css";
import type { CSSProperties } from "react";
import { WorkspaceProvider } from "../components/workspace/WorkspaceContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
      style={{ "--sidebar-width": "18rem" } as CSSProperties}
    >
      <body className="min-h-full flex flex-col">
        <WorkspaceProvider>{children}</WorkspaceProvider>
      </body>
    </html>
  );
}
